; =====================================================================
; SMHUB RTOS DEV Workspace - PlatformIO Override Configuration Template
; =====================================================================

[env:rtos-smhub]
; Use the local Git submodules cloned inside src/
platform = symlink:///workspaces/smhub-rtos-dev/src/platform-sg2000
platform_packages =
    framework-sg2000-rtos @ symlink:///workspaces/smhub-rtos-dev/src/framework-sg2000-rtos

[env:rtos-nano]
; Use the local Git submodules cloned inside src/
platform = symlink:///workspaces/smhub-rtos-dev/src/platform-sg2000
platform_packages =
    framework-sg2000-rtos @ symlink:///workspaces/smhub-rtos-dev/src/framework-sg2000-rtos
